### ISSUE TITLE
XML looses attributes when parsed

### ISSUE THREAD

**Issue by Razzeee** [nathanmac/Parser#17]
Thank you for this great tool.

I really hope I haven't overlooked this, but I have an XML as follows:

```
<extension point="whatever">
   <summary lang="bg">FAFSSAFA</summary>
   <summary lang="ca">OIGOIEWG</summary>
   <summary lang="cs">KGJWOIGJW</summary>
</extension>
```

So if I parse it, I can get the attributes of the extension. But summary gets grouped to an array and the attributes (bg, ca, cs) get lost.

```
[@attributes] => Array
    (
        [point] => whatever
    )

[summary] => Array
    (
        [0] => FAFSSAFA
        [1] => OIGOIEWG
        [2] => KGJWOIGJW
    )
```

**Comment by mattvb91** [comment]
Same issue here

**Comment by nathanmac** [comment]
The attributes problem was added as a sort of compromise because it is difficult to keep the standard output structure across the different language types.

The library was designed around handling situations where an API could support multiple content types as input for example

```json
{
    "extension": {
        "summary": [
            "FAFSSAFA",
            "OIGOIEWG",
            "KGJWOIGJW"
        ]
    }
}
```

should be the same as 

```xml
<extension>
   <summary>FAFSSAFA</summary>
   <summary>OIGOIEWG</summary>
   <summary>KGJWOIGJW</summary>
</extension>
```

I think it would require quite a major change to the output Array which is possible but I guess there may already be different libraries which can specifically process xml data.

Any suggestions on the possible output structure? more than welcome.

**Comment by Razzeee** [comment]
to be honest, I'm not sure, as I'm normally not working with php

**Comment by nathanmac** [comment]
Might be worth looking at http://sabre.io/xml/ package if your looking to parse more complex xml with support for attributes and namespacing.
