### ISSUE TITLE
Parser::only('something') does not work?

### ISSUE THREAD

**Issue by andreasba** [nathanmac/Parser#18]
Good evening,

not sure whether I am simply too stupid but when I apply the only method to my parsed payload the returned array is always null, no matter whether I try to do it via facade (Laravel 5.1) or the OOP way:

```PHP
\Parser::xml(($response->getBody()->getContents()));
$test = \Parser::only('Order'); // null!
```

```PHP
$parser = new Parser();
$orders = $parser->xml(($response->getBody()->getContents()))->only('Order'); // also null
```

What am I doing wrong? Or is this a bug? :-)

Thanks anyway for the beautiful and easy to use parser!

Andreas

PS: Of course the outputted XML contains a "Order" key on the second level but also "first level" keys do not work

**Comment by nathanmac** [comment]
@andreasba could you provide a sample of the xml your trying to parse and I will attempt to verify this issue and implement as fix.

Thanks.

**Comment by andreasba** [comment]
Sure @nathanmac - check your mail :)

**Comment by nathanmac** [comment]
@andreasba I see what the problem is the `only` methods are available when the input is being auto-detected and loaded from the http request.

Chaining the `only` method is not available because its an array at this point not an object.

I do think it would be a good addition to support something like this but in the meantime properly the best option would be to transform the array returned in to a illuminate collection object, that way you have access to all the supported functions documented here: http://laravel.com/docs/5.1/collections#available-methods

```php
$parser = new Parser();
$orders = $parser->xml(($response->getBody()->getContents())); // <-- Array

$collection = new \Illuminate\Support\Collection($orders['order']);

return $collection->only(['item', 'price', 'timestamp']);
```
