### ISSUE TITLE
Laravel 5.1 error

### ISSUE THREAD

**Issue by fscaptain** [nathanmac/Parser#19]
Hi,

setting up as shown but get the follwoing error on laravel 5.1 :

Call to undefined method Nathanmac\Utilities\Parser\Facades\Parser::xml()

Thanks Marco

**Comment by nathanmac** [comment]
Hi @fscaptain, have you added the service provider and/or alias in the `app/config/app.php` file?

**Comment by fscaptain** [comment]
Really, as described in the readme. Should it be that this may be wrong, because all others entries there are slighly different ?

**Comment by andreasba** [comment]
Did you try to escape the Classname like in

```PHP
$xml = Parser::xml(($response->getBody()->getContents()));
```

?

I am running Parser on Laravel 5.1.26 without problems

Andreas

**Comment by fscaptain** [comment]
Hi, in this way it works also for me, but if i try to use the alias it comes ot the error.

**Comment by sergchernata** [comment]
Having the same issue on Laravel 5.3

Calling this:
```
$parser = new Parser();
$parser->xml($xml);
```

results in:
    Call to undefined method Nathanmac\Utilities\Parser\Facades\Parser::xml()

However, this works:
```
Parser::xml($xml);
```

**Comment by danhunsaker** [comment]
@sergchernata - That appears to be working how Laravel Facades are meant to, yes - a Facade gives you a static interface to a common instance of an object, so you don't have to recreate it in, or pass it around to, every method you want to use it in.

If you want to use a regular object instead of a Facade, add `use Nathanmac\Utilities\Parser\Parser;` at the beginning of each file you want to use it in (instead of `use Parser;`, which will grab the Facade instead).

I agree the README is more than a little vague on this front.  I'll see if I can clean it up some.

@fscaptain - I expect, since it's been about a year, that you aren't having this issue any more, likely because you're using something else to handle parsing, but if your troubles came from the same place, your solution should be the same, too.  Either use the regular object directly along with `new`, or treat the Facade as a static interface to a singleton.  Again, I'll see if I can submit a PR to update the README on this bit.
